### ISSUE TITLE
Does not work if there is not already another window open

### ISSUE THREAD

**Issue by arnoo** [mhammond/firefox-pinned-windows#1]
Hi,

This extension is absolutely awesome, it's what I've been looking for for a long time.

It seems to me though that when the pinned window is the only open Firefox window, clicking on a link or creating a new tab should open a new Firefox window, instead of creating a tab in the current (pinned) window ?

**Comment by mhammond** [comment]
Yeah, it should!

**Comment by mhammond** [comment]
Fixed in revision 855d7f018670ab804d10d7fa1b42c381642c4e83 and new version uploaded and waiting on review.
